---

# Used by aws cli with sudo commands
# If you are not able to change sudo_flags, the HOME variable when using become_user
# will be the HOME from the ssh user.
- name: "Get HOME directory for user {{ backup_mongo_cron_user }}"
  shell: 'getent passwd {{ backup_mongo_cron_user }} | cut -d: -f6'
  register: user_home

- name: Validate create tmpfile to test s3 push.
  file: path=/tmp/ansible-backup-mongo.test state=touch
- debug: var=backup_mongo_cron_user

# Use command instead of s3 module was made to test exactly the command that the cron will execute
- name: Validate the cron user can push into the bucket with s3cmd
  command: aws s3 cp /tmp/ansible-backup-mongo.test s3://{{ backup_mongo_bucket_name }}
  become: yes
  become_user: "{{ backup_mongo_cron_user }}"
  environment:
    HOME: "{{ user_home.stdout }}"

- name: Validate the file is uploaded
  command: aws s3 ls s3://{{ backup_mongo_bucket_name }}/ansible-backup-mongo.test
  become: yes
  become_user: "{{ backup_mongo_cron_user }}"
  environment:
    HOME: "{{ user_home.stdout }}"

- name: Validate cleanup test file in s3
  command: aws s3 rm s3://{{ backup_mongo_bucket_name }}/ansible-backup-mongo.test
  become: yes
  become_user: "{{ backup_mongo_cron_user }}"
  environment:
    HOME: "{{ user_home.stdout }}"
  run_once: true
