---

- name: "Install required package for mysql backup | Ubuntu / Debian"
  apt:
    name: '{{ item }}'
    cache_valid_time: 3600
    update_cache: yes
    state: latest
  with_items:
    - cron
    - python-dev
    - build-essential
    - python-pip
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: "Install required package for mysql backup | Ubuntu / Debian 9"
  apt:
    name: '{{ item }}'
    cache_valid_time: 3600
    update_cache: yes
    state: latest
  with_items:
    - mysql-client
  when: ansible_distribution == 'Ubuntu' or ansible_distribution_version < '10'

- name: "Install required package for mysql backup Debian 10"
  apt:
    name: '{{ item }}'
    cache_valid_time: 3600
    update_cache: yes
    state: latest
  with_items:
    - default-mysql-client
  when: ansible_distribution == 'Debian' and ansible_distribution_version >= '10'

- pip: name=awscli state=latest
  when: _check_aws_cli|failed

# Ensure dateutil is installed for s3_lifecycle
- pip: name=python-dateutil state=present
  run_once: true
  delegate_to: 127.0.0.1
