---

- name: "Apply s3 backup lifecycle policy on the s3 bucket {{ backup_es_bucket_name }}"
  s3_lifecycle:
    rule_id: "{{ _backup_s3_expire_policy.name }}"
    name: "{{ backup_es_bucket_name }}"
    transition_days: "{{ _backup_s3_expire_policy.glacier_transition }}"
    expiration_days: "{{ _backup_s3_expire_policy.permanently_delete }}"
    prefix: "{{ _backup_s3_expire_policy.prefix }}"
    status: enabled
    state: present
  run_once: true
  delegate_to: 127.0.0.1
  when: _backup_s3_expire_policy.glacier_transition > 0

- name: "Apply s3 backup lifecycle policy on the s3 bucket {{ backup_es_bucket_name }}"
  s3_lifecycle:
    rule_id: "{{ _backup_s3_expire_policy.name }}"
    name: "{{ backup_es_bucket_name }}"
    expiration_days: "{{ _backup_s3_expire_policy.permanently_delete }}"
    prefix: "{{ _backup_s3_expire_policy.prefix }}"
    status: enabled
    state: present
  run_once: true
  delegate_to: 127.0.0.1
  when: _backup_s3_expire_policy.glacier_transition == 0 and _backup_s3_expire_policy.permanently_delete > 0

- name: "Add elasticsearch backup script /usr/bin/elasticsearch-backup.sh"
  template: src="{{ ansible_template_path_legacy }}elasticsearch/elasticsearch-backup.sh.j2" dest=/usr/bin/elasticsearch-backup.sh owner=root group=root mode=0755

- name: "Add elasticsearch repository creation script /usr/bin/elasticsearch-create-backup-repository.sh"
  template: src="{{ ansible_template_path_legacy }}elasticsearch/elasticsearch-create-backup-repository.sh.j2" dest=/usr/bin/elasticsearch-create-backup-repository.sh owner=root group=root mode=0755

# Configure backups
- name: "ES repository {{ backup_es_repository_name }} exist ?"
  uri:
    url: "http://{{ backup_es_host }}:{{ backup_es_port }}/_snapshot/{{ backup_es_repository_name }}"
    method: GET
    status_code: 200
  ignore_errors: True
  register: backup_es_repository_status

- name: "Create ES repository {{ backup_es_repository_name }}"
  command: /usr/bin/elasticsearch-create-backup-repository.sh
  when: backup_es_repository_status is failed

# Add cron comands
- name: "cron add snapshot and retention commands"
  block:
    - cron:
        name: "{{ item.name | default(default_backup_es_cron.name) }}"
        job: "{{ item.job | default(default_backup_es_cron.job) }}"
        minute: "{{ item.minute | default(default_backup_es_cron.minute) }}"
        hour: "{{ item.hour | default(default_backup_es_cron.hour) }}"
        day: "{{ item.day | default(default_backup_es_cron.day) }}"
        month: "{{ item.month | default(default_backup_es_cron.month) }}"
        weekday: "{{ item.weekday | default(default_backup_es_cron.weekday) }}"
        cron_file: "{{ item.file | default(default_backup_es_cron.cron_file) }}"
        user: "{{ item.user | default(default_backup_es_cron.user) }}"
        state: "{{ item.state | default(default_backup_es_cron.state) }}"
      with_items:
        - "{{ backup_es_cron }}"
    - cron:
        env: yes
        name: PATH
        value: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        cron_file: "{{ item.file | default(default_backup_es_cron.cron_file) }}"
        user: "{{ item.user | default(default_backup_es_cron.user) }}"
        state: "{{ item.state | default(default_backup_es_cron.state) }}"
      with_items:
        - "{{ backup_es_cron }}"
  become: yes 

